2025-09-09 03:26:54,232 |    ERROR | clever_ai | error:128 | [CONVERSATION] Error in process_conversation | Data: {"duration": "0.0000s", "args_count": 5, "kwargs": []} | Error: 'float' object has no attribute 'get'
2025-09-09 03:26:54,233 |    ERROR | clever_ai | error:129 | Traceback: Traceback (most recent call last):
  File "/workspaces/projects/debug_config.py", line 223, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/projects/clever_conversation_engine.py", line 113, in process_conversation
    self._update_clever_emotional_state(analysis, response_approach)
  File "/workspaces/projects/clever_conversation_engine.py", line 178, in _update_clever_emotional_state
    sentiment = analysis.get('sentiment', {}).get('compound', 0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'get'

